name: 'Validate Tapyr App'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Run quality checks
        uses: devcontainers/ci@v0.3
        with:
          runCmd: ./quality_checks.sh
