name: 'Test PyShiny App'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: ./run_tests_and_bandit.sh
